### ISSUE TITLE
Does not work with group chat

### ISSUE THREAD

**Issue by juanmbellini** [kvld/travisci-telegram#1]
It is invited to the group, but it does not notify

**Comment by vudaltsov** [comment]
@kvld, Владислав, спасибо за бота!
Но в группах реально не работает, поправьте, пожалуйста :)

**Comment by juanmbellini** [comment]
English please 😀

**Comment by vudaltsov** [comment]
@juanmbellini , no problem I just thought native language will be more motivating 😆

**Comment by mortum5** [comment]
@juanmbellini , can you describe problem in details? I have no problem with this from mobile and from desktop also, but i know about bug in MacOs, when you have link to add bot to the group, but nothing happens where you click on link, is it your situation?

**Comment by vudaltsov** [comment]
@mortum, it's my case as well. Tried adding bot from Android instead of Mac and it worked! Thanks a lot!

**Comment by juanmbellini** [comment]
I can add the bot to a group chat, but I can't link it with nothing.

**Comment by mortum5** [comment]
@juanmbellini , It isn't bug, just use bot from private chat and choose notification to group.
