### ISSUE TITLE
Bot unavailable

### ISSUE THREAD

**Issue by dmitmel** [kvld/travisci-telegram#2]
On April 29, there was a massive massive power outage in the Amsterdam region that [affected Telegram servers](https://twitter.com/telegram/status/990474364108894209). This caused `api.telegram.org` to respond with the `502 Bad Gateway` HTTP error on every request. _**Maybe**_, because of this **@travisci_build_bot** has crashed. So now it does not respond to any message. Could you, please, restart the bot?

**Comment by kvld** [comment]
Sorry for late reply, but it works now, right?

**Comment by dmitmel** [comment]
Yes, it actually works now.
